### ISSUE TITLE
Not exactly 1000 videos per action?

### ISSUE THREAD

**Issue by mahyarkoy** [huangjiadidi/DeepFakeMinst#3]
Hi, thank you for a great dataset. I am seeing the following number of videos per action, and it was not exactly 1000 videos each. Can you clarify what are the extra videos and how come mouth has 999 videos? I just wanted to make sure I'm not using a wrong version of the dataset. Thanks.

blink has 1000 videos.
yaw has 1053 videos.
surpise has 1004 videos.
mouth has 999 videos.
up has 1085 videos.
right_slope has 1007 videos.
embarrass has 1008 videos.
nod has 1261 videos.
left_slope has 1021 videos.
smile has 1040 videos.

**Comment by huangjiadidi** [comment]
Hi! It is a mistake that I uploaded the incorrect version of the dataset. I have updated the download link. Please check that. I also include the real(unmodified) data in the folder.

Thank you
